# Generated by Django 3.2.4 on 2021-06-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="sub_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.sub_subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.subject"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(through="home.Question_Tag", to="home.Tag"),
        ),
        migrations.AddField(
            model_name="book",
            name="related_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.subject"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="user_answer_dislikes", to="users.Profile"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="user_answer_likes", to="users.Profile"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.question"
            ),
        ),
        migrations.AddConstraint(
            model_name="sub_subject",
            constraint=models.UniqueConstraint(
                fields=("sub_subject_name", "related_subject"),
                name="unique_sub_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="question_tag",
            constraint=models.UniqueConstraint(
                fields=("question", "tag"), name="question_tag"
            ),
        ),
    ]
