# Generated by Django 3.1.7 on 2021-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_question_tag"),
        ("home", "0008_test_data_answer"),
    ]

    operations = []
