# Generated by Django 3.1.7 on 2021-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20210410_1711'),
        ('home', '0009_test_data_tag_question_tag'),
    ]

    operations = [
    ]
