# Generated by Django 3.2 on 2021-04-30 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_add_answers_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='book_page',
            field=models.IntegerField(blank=True,
                                      null=True,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(999)]),
        ),
    ]
