# Generated by Django 3.2.2 on 2021-05-10 10:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_question_book_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
