# Generated by Django 3.2.3 on 2021-05-20 07:51

from django.db import migrations
import home.RichTextBleachField


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_add_tags_test_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=home.RichTextBleachField.RichTextBleachField(blank=True, null=True),
        ),
    ]
