# Generated by Django 3.2.3 on 2021-05-20 09:49

from django.db import migrations
import home.RichTextBleachField


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_question_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=home.RichTextBleachField.RichTextBleachField(blank=True, null=True),
        ),
    ]
