# Generated by Django 3.2.4 on 2021-06-18 05:45

from django.db import migrations
import home.RichTextBleachField


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_question_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=home.RichTextBleachField.RichTextBleachField(default=""),
        ),
    ]
